language: python
sudo: false
python: 2.7
install: pip install tox coveralls
script: tox -e $TOX_ENV
after_success: coveralls
before_script:
    - cp t_overrides.travis.py t_overrides.py
    - psql -U postgres -c "DROP DATABASE IF EXISTS multigtfs"
    - psql -U postgres -c "CREATE DATABASE multigtfs"
    - psql -U postgres -d multigtfs -c "CREATE EXTENSION IF NOT EXISTS postgis; CREATE EXTENSION IF NOT EXISTS postgis_topology;"
env:
    - TOX_ENV=py27-django18-postgis
    - TOX_ENV=py34-django17-postgis
    - TOX_ENV=py34-django18-postgis
    - TOX_ENV=py27-django19-postgis
    - TOX_ENV=py34-django19-postgis
    - TOX_ENV=py35-django19-postgis
    - TOX_ENV=py27-django110-postgis
    - TOX_ENV=py34-django110-postgis
    - TOX_ENV=py35-django110-postgis
    - TOX_ENV=py27-djangomaster-postgis
    - TOX_ENV=py34-djangomaster-postgis
    - TOX_ENV=py35-djangomaster-postgis
matrix:
    allow_failures:
        # Django master is allowed to fail
        - env: TOXENV=py27-djangomaster-postgis
        - env: TOXENV=py34-djangomaster-postgis
        - env: TOXENV=py35-djangomaster-postgis
